
# Replace the values in the fields below with your own info so the scraper can send out emails.

# "sender" is the email address that will be sending out the emails. I made a throwaway gmail account for this.
# "password" is the password for the sender account.
# "receiver" is the email address that the sender email account will be sending the email to.
# "smtp server" is the smtp server the sender email account uses. If the sender email is a gmail address you do not need to change this.
# "smtp port" is the port the above smtp server uses. If the sender email is a gmail address you do not need to change this.

from: sender@example.com
username: sender@example.com
password: Sender Password
receiver: receiver@example.com
smtp server: smtp.gmail.com
smtp port: 465

---
# Set the URLs you wish to scrape below with an optional list of words to exclude per URL.
# Any filters you apply on the Kijij website are a part of the URL and will apply to the scraper.
# "url" is as you would guess the URL you want to scrape.
# "exclude" is a list of words, if an ad title contains any one of the words it will be ignored. Add as many words as you desire.

# There are a couple examples below which you will want to remove/replace with your own.
# You can add as many URLs as you wish to scrape.

# URLs to scrape
# teak furniture
# midcentury buy and sell
# midcentury real estate
- url: https://www.kijiji.ca/b-buy-sell/calgary/teak/k0c10l1700199?rb=true&ll=51.044733%2C-114.071883&address=Calgary%2C+AB&radius=50.0
  pages: 2
  exclude:
    - kollektion
    - ella grace
- url: https://www.kijiji.ca/b-buy-sell/calgary/midcentury/k0c10l1700199?rb=true&ll=51.044733%2C-114.071883&address=Calgary%2C+AB&radius=50.0
  pages: 2
  exclude:
    - kollektion
    - ella grace
- url: https://www.kijiji.ca/b-real-estate/calgary/midcentury/k0c34l1700199?ll=51.044733%2C-114.071883&address=Calgary%2C+AB&radius=50.0
  pages: 2
  exclude:
    - kollektion
    - ella grace
- url: https://www.kijiji.ca/b-buy-sell/calgary/danish/k0c10l1700199?rb=true&ll=51.044733%2C-114.071883&address=Calgary%2C+AB&radius=50.0
  pages: 2
  exclude:
    - kollektion
    - ella grace
- url: https://www.kijiji.ca/b-buy-sell/calgary/denmark/k0c10l1700199?rb=true&ll=51.044733%2C-114.071883&address=Calgary%2C+AB&radius=50.0
  pages: 2
  exclude:
    - kollektion
    - ella grace
- url: https://www.kijiji.ca/b-furniture/calgary/c235l1700199?ll=51.044733%2C-114.071883&address=Calgary%2C+AB&radius=50.0
  pages: 2
  exclude:
    - Kollektion
    - Mahogany
    - Oak
    - Walnut
    - Cherry
    - Pine
    - Elm
    - birch
    - Ella grace
    - Ikea
    - Office
    - Hepburn
    - Victorian
    - Mattress
    - Box spring
    - Rustic
    - Lazy
    - Revolve
    - Bouclair
    - Brick
    - Sleigh
    - Bunk
    - Eq3
    - West elm
    - Cb2
    - barn
    - Barrell
    - Barcelona
    - Wayfair
    - Walmart
    - Baby
    - Kids
    - Jysk
    - computer
    - twin
    - kallax
    - TV
    - faux
    - fire table
    - fireplace
    - firepit
    - wrought iron
    - bean bag
    - beanbag
    - Ashley
    - brand new
    - Structube
    - Natuzzi
    - Bed frame
    - Box
    - Brand new
    - Sectional
    - French
    - Provincial
    - Farmhouse
    - Ladder
    - Game
    - Gaming
    - Best selling
    - Shoe
    - Rack
    - shoerack
    - Glider
    - Structube
    - Cedar
    - Spruce
    - Desk chair
    - Massage
    - Queen Anne
    - Ethan Allen
    - Sklar
    - Maple
    - Microfibre
    - Microfiber
    - Reclaimed
    - Painted
    - La-z-boy
    - Pool table
    - Power
    - Oak
    - Papasan
    - Futon
    - Epoxy
    - Beach
    - Camping
    - Sofa bed
    - Lawn
    - Mattresses
    - Ashley
    - Filing
    - File cabinet
    - Trunk
    - Clearance
    - Farm house
    - Murphy
    - Heavy duty
    - Floral
    - Memory foam
    - Pull out
    - Pullout
    - Iron
    - Conference
    - Laminate
    - Tufted headboard
    - Boxspring
    - Loft bed
    - Folding table
    - Bamboo
    - Standing desk
    - Industrial
    - Pier
    - Child
    - Barrel
    - 4038285672

# Url with exclude words given
# - url: https://www.kijiji.ca/b-cars-trucks/alberta/tesla-new__used/c174l9003a54a49
#   exclude:
#     - wanted
#     - gas
#     - base
